/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.6.1/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    alias(libs.plugins.kotlin.jvm)

    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    implementation(libs.ktor.server.core)
    implementation(libs.ktor.server.cio)
    implementation(libs.ktor.server.html.builder)
    implementation(libs.ktor.server.config.yaml)
    implementation(libs.ktor.htmx)
    implementation(libs.ktor.htmx.html)
    implementation(libs.ktor.server.htmx)
    implementation(libs.ktor.server.status.pages)

    implementation(libs.ktor.client.core)
    implementation(libs.ktor.client.cio)
    implementation(libs.ktor.client.content.negotiation)
    implementation(libs.ktor.serialization.kotlinx.json)

    implementation(libs.kotlinx.kotlinxHtml)

    implementation(libs.exposed.core)
    implementation(libs.exposed.jdbc)
    implementation(libs.h2)

    implementation(libs.logback.classic)
}

// Apply a specific Java toolchain to ease working on different environments.
kotlin {
    jvmToolchain(21)
}

application {
    // Define the main class for the application.
    mainClass = "io.ktor.server.cio.EngineMain"
}

// Used by dev.sh to launch the app directly with `java`, bypassing Gradle's
// daemon-managed JavaExec so a file watcher can reliably kill/restart it.
tasks.register("printRuntimeClasspath") {
    doLast {
        println(sourceSets.main.get().runtimeClasspath.asPath)
    }
}
