#!/bin/bash
# Generated By Claude Sonnet 5
#
# Dev workflow with reliable restart-on-save.
#
# Why not `./gradlew run`? Ktor's own in-process autoreload only fires once
# per run and then goes silent (a known one-shot watcher bug), and Gradle's
# daemon-managed JavaExec can't be reliably killed/restarted by an external
# file watcher either. This script sidesteps both: Gradle keeps recompiling
# in the background, and a plain `java` process (which a file watcher CAN
# kill cleanly) gets fully restarted on every change.
#
# Requires `entr` (brew install entr).
set -euo pipefail
cd "$(dirname "$0")"

if ! command -v entr >/dev/null; then
    echo "entr is required: brew install entr" >&2
    exit 1
fi

echo "Resolving runtime classpath..."
CLASSPATH=$(./gradlew -q printRuntimeClasspath)

echo "Starting continuous compile..."
./gradlew -t classes &
COMPILE_PID=$!

cleanup() {
    kill "$COMPILE_PID" 2>/dev/null || true
}
trap cleanup EXIT

echo "Watching for changes (Ctrl+C to stop)..."
find build/classes src/main/resources -type f 2>/dev/null | \
    entr -rn java -cp "$CLASSPATH" io.ktor.server.cio.EngineMain
