ktor:
  deployment:
    port: ${PORT}
  application:
    modules:
      - findee.AppKt.configureRouting
      - findee.AppKt.configureStatusPages
      - findee.AppKt.monitors
      - findee.AppKt.dbConnect
  
  db:
    dir: ${DB_DIR}
  client:
    simplefin_url: ${SIMPLEFIN_URL}
    simplefin_username: ${SIMPLEFIN_USERNAME} 
    simplefin_password: ${SIMPLEFIN_PASSWORD} 